# options 0 = pass, 1 = warning, 2 = error, https://github.com/sasstools/sass-lint/tree/master/docs/rules
options:
  formatter: stylish
  merge-default-rules: false
files:
  ignore:
    - '_includes/**/*.html'
    - 'node_modules/**/*.*'
    - '_scss/vendors/*.*'
    - 'dist/**/*.*'
rules:
  brace-style:
    - 2
    - style: '1tbs'
    - allow-single-line: false
  class-name-format:
    - 2
    - convention: ^[\-_a-zA-Z0-9]+$
    - convention-explanation: 'Class must contain only letters, numbers and dashes'
  empty-line-between-blocks:
    - 2
    - allow-single-line-rulesets: false
  final-newline:
    - 2
    - include: true
  hex-notation:
    - 2
    - style: uppercase
  indentation:
    - 2
    - size: 4
  leading-zero:
      - 2
      - include: false
  nesting-depth:
    - 2
    - max-depth: 4
  no-duplicate-properties:
  - 1
  -
    exclude:
      - src
  no-color-keywords: 2
  no-color-literals:
    - 2
    - allow-rgba: true
  no-important: 0
  no-ids: 2
  no-qualifying-elements: 0
  no-trailing-whitespace: 2
  no-vendor-prefixes: 2
  one-declaration-per-line:
    - 2
    - include: true
  quotes:
    - 2
    - mode: single
  single-line-per-selector: 2
  space-after-colon:
    - 2
    - include: true
  space-after-comma:
    - 2
    - include: true
  space-before-brace:
    - 2
    - include: true
  zero-unit: 2